#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys,os,urllib,urllib2,ssl,re,time,readline#,getch
from pygame import mixer
#from threading import Thread
if os.name=="nt":
	print "Windows isn't supported."
	SystemExit
v="1.6.9"
class bcolors:
	HEADER = '\033[95m'
	OKBLUE = '\033[94m'
	OKGREEN = '\033[92m'
	WARNING = '\033[93m'
	FAIL = '\033[91m'
	ENDC = '\033[0m'
	BOLD = '\033[1m'
	UNDERLINE = '\033[4m'
	BL = '\033[30m'
	BW = '\033[47m'
def trow():
	return int(os.popen('stty size','r').read().split()[0])
def tcol():
	return int(os.popen('stty size','r').read().split()[1])
def cls():
	os.system('cls' if os.name=='nt' else 'clear')
def hr():
	#return "-"*tcol()
	return "─"*tcol()
clist=[".history",".history -c","s",".set","exit",".exit","quit",".quit",".v"]
for a in range(50):
	clist.append(str(a))
	clist.append("d "+str(a))
class MyCompleter(object):  # Custom completer
	def __init__(self, options):
		self.options = sorted(options)
	def complete(self, text, state):
		if state == 0:  # on first trigger, build possible matches
			if text:  # cache matches (entries that start with entered text)
				self.matches = [s for s in self.options 
									if s and s.startswith(text)]
			else:  # no text entered, all matches possible
				self.matches = self.options[:]
		# return match indexed by state
		try: 
			return self.matches[state]
		except IndexError:
			return None
completer = MyCompleter(clist)
readline.set_completer(completer.complete)
readline.parse_and_bind('tab: complete')
def gv(text):
	return urllib.urlencode({"a":text})[2:]
def ungv(text):
	return urllib.unquote(text.replace("+"," "))
def rr(results,p):
	global st
	global n
	if p=="<":
		if n<=10:
			print "No more page back."
		else:
			cls()
			print st+"\n"+hr()
			n-=20
			if n<0:
				n=0
			tn=n+10
			while n<len(results) and n<tn:
				if n%2==0:
					#print bcolors.BW+bcolors.BL+str(n)+"-"+"".join(re.findall('&raquo;">(.*?)</a>',r[n]))+"-"+"".join(re.findall('&ndash; (.*?)</span>',r[n]))+"-"+"".join(re.findall('span class="dur">(.*?)</span>',r[n]))+bcolors.ENDC
					print bcolors.BW+bcolors.BL+str(n)+"-"+r[n]+"-"+rn[n]+"-"+rt[n]+bcolors.ENDC
				else:
					#print str(n)+"-"+"".join(re.findall('&raquo;">(.*?)</a>',r[n]))+"-"+"".join(re.findall('&ndash; (.*?)</span>',r[n]))+"-"+"".join(re.findall('span class="dur">(.*?)</span>',r[n]))
					print str(n)+"-"+r[n]+"-"+rn[n]+"-"+rt[n]
				n+=1
			print "< page "+str(n/10)+"/"+str(len(results)/10)+" >"
	else:
		if n>=len(results):
			print "No more page."
		else:
			cls()
			print st+"\n"+hr()
			tn=n+10
			while n<len(results) and n<tn:
				if n%2==0:
					#print bcolors.BW+bcolors.BL+str(n)+"-"+"".join(re.findall('&raquo;">(.*?)</a>',r[n]))+"-"+"".join(re.findall('&ndash; (.*?)</span>',r[n]))+"-"+"".join(re.findall('span class="dur">(.*?)</span>',r[n]))+bcolors.ENDC
					print bcolors.BW+bcolors.BL+str(n)+"-"+r[n]+"-"+rn[n]+"-"+rt[n]+bcolors.ENDC
				else:
					#print str(n)+"-"+"".join(re.findall('&raquo;">(.*?)</a>',r[n]))+"-"+"".join(re.findall('&ndash; (.*?)</span>',r[n]))+"-"+"".join(re.findall('span class="dur">(.*?)</span>',r[n]))
					print str(n)+"-"+r[n]+"-"+rn[n]+"-"+rt[n]
				n+=1
			print "< page "+str(n/10)+"/"+str(len(results)/10)+" >"
"""def gr(results,num,w):
	wr="".join(re.findall('&raquo;">(.*?)</a>',results[num]))+"-"+"".join(re.findall('&ndash; (.*?)</span>',results[num]))+"-"+"".join(re.findall('span class="dur">(.*?)</span>',results[num]))
	if w=="s":
		return wr.split("-")[0]
	if w=="n":
		return wr.split("-")[1:-1]
	if w=="t":
		return wr.split("-")[-1]
	else:
		return wr"""
global ms
ms=""
"""def kpress():
	global ms
	while time.time()-start<=durat and ms!="stop":
		key=getch.getch()
		if key==" ":
			if ms=="play":
				mixer.music.pause()
				ms="pause"
			else:
				mixer.music.unpause()
				ms="play"
		elif key=="q":
			mixer.music.stop()
			ms="stop"""
def bar():
	global ms
	while time.time()-start<=durat and ms!="stop":
		ts=" "+str(int(time.time()-start))+"/"+str(durat)+" "+str((int(time.time()-start)*100)/durat)+"%"
		bar="["+"="*((((tcol()-len(ts)-2)*(int(time.time()-start)*100)/durat))/100)
		print ts+bar+" "*(tcol()-len(ts)-len(bar)-1)+"]"+"\r",
		sys.stdout.flush()
		time.sleep(1)
def strm(pathto,linkdwn):
	f=open(pathto,"w")
	f.write(linkdwn.read())
	f.close()
def plm(pathload,mdu):
	try:
		mixer.init()
		mixer.music.load(pathload)
		mixer.music.play()
		global start
		start=time.time()
		global durat
		durat=mdu
		ms="play"
		while time.time()-start<=durat and ms!="stop":
			bar()
			#tbr=Thread(target=bar()).start()
			#tkp=Thread(target=kpress()).start()
		#tkp.do_run=False
		#tbr.do_run=False
		if ms=="stop":
			print "\nStop."
		else:
			print "\nEnd."
	except KeyboardInterrupt:
		print "\nStop."
		mixer.music.stop()
		ms="stop"
		#tkp.do_run=False
		#tbr.do_run=False
		if os.path.isfile(pathload):
			os.remove(pathload)
def wsm():
	if not os.path.isfile(os.path.expanduser("~")+"/.mux/set.conf"):
		wsm="./"
	else:
		sett=open(os.path.expanduser("~")+"/.mux/set.conf","r")
		cset=sett.read()
		sett.close()
		wsm="".join(re.findall('saveto=(.*?);',cset))
		if not wsm.endswith("/"):
			wsm+="/"
	return wsm
ctx=ssl.create_default_context()
ctx.check_hostname=False
ctx.verify_mode=ssl.CERT_NONE
url="https://petapleer.ru/"
print "Connecting..."
try:
	urllib.urlopen(url)
	print "Ok"
except Exception as e:
	print "Error:\n"+str(e)
	sys.exit()
if os.path.isfile(os.path.expanduser("~")+"/.mux/history.log"):
	whis=open(os.path.expanduser("~")+"/.mux/history.log","a")
else:
	whis=""
e=True
while e:
	cls()
	if tcol()>=17:
		sp=int((tcol()-17)/2)
		print bcolors.OKGREEN+" "*sp+" _  _  _ _ __  __"
		print " "*sp+"| \/ || | |\ \/ /"
		print " "*sp+"|    || | | \  /"
		print " "*sp+"| \/ || | | /  \\"
		print " "*sp+"|_||_||___|/_/\_\\"
		print " "*sp+"music plyr/dwnldr"+bcolors.ENDC
	else:
		sp=int((tcol()-3)/2)
		print bcolors.OKGREEN+" "*sp+"MUX"+bcolors.ENDC
	if os.path.isfile("/usr/local/bin/mux"):
		print " "*int((tcol()-len("v"+v))/2)+bcolors.OKBLUE+"v"+v+bcolors.ENDC
	else:
		print " "*int((tcol()-len("v"+v+" not installed"))/2)+bcolors.OKBLUE+"v"+v+bcolors.FAIL+" not installed"+bcolors.ENDC
	q=raw_input("Search: ")
	if q==".set":
		cls()
		if not os.path.isfile(os.path.expanduser("~")+"/.mux/set.conf"):
			sett=open(os.path.expanduser("~")+"/.mux/set.conf","w+")
			sett.write("user="+os.environ["USER"]+";\ninstalled="+time.time()+";saveto=.;")
			sett.close()
		print "Settings ("+os.path.expanduser("~")+"/.mux/set.conf):"
		sett=open(os.path.expanduser("~")+"/.mux/set.conf","r")
		cset=sett.read()
		sett.close()
		ocs="".join(re.findall('saveto=(.*?);',cset))
		print "Save music at:",ocs
		cs=raw_input("Change with: ")
		cs.replace("~",os.path.expanduser("~"))
		if cs=="":
			cs=ocs
		cset=cset.replace("saveto="+ocs+";","saveto="+cs+";")
		sett=open(os.path.expanduser("~")+"/.mux/set.conf","w")
		sett.write(cset)
		sett.close()
		raw_input("<ENTER> to continue")
	elif q==".v":
		print "You are using: "+bcolors.OKBLUE+"v"+v+bcolors.ENDC
		llc=urllib.urlopen("https://raw.githubusercontent.com/Bytezz/mux/master/mux").read()
		lc=llc.replace("\n","")
		if not 'v="' in lc:
			lv="0.1"
		else:
			for line in llc.splitlines():
				if 'v="' in line:
					lv="".join(re.findall('v="(.*?)"',line))
					break
		print "Latest: "+bcolors.OKBLUE+"v"+lv+bcolors.ENDC
		if float(v.split(".")[0]+"."+"".join(v.split(".")[1:]))<float(lv.split(".")[0]+"."+"".join(lv.split(".")[1:])):
			print bcolors.FAIL+"Your software isn't up to date."+bcolors.ENDC
			cvs=os.path.getsize(os.path.realpath(__file__))
			lvs=len(llc)
			if lvs>=cvs:
				ssp=str(lvs-cvs)+"B more"
			else:
				ssp=str(cvs-lvs)+"B less"
			up=raw_input("Update? ("+str(lvs)+"B, "+ssp+") [y or n]: ")
			if up.lower()=="y" or up.lower()=="yes":
				try:
					print "Update..."
					os.system("git clone https://github.com/Bytezz/mux temp && cd temp/ && mv ../temp/* .. && rm -rf ../temp")
					print "Completed."
					print "To install updates run:\nsudo make reinstall"
				except:
					print "Git not installed."
					print "Go here for download:"
					print "https://github.com/Bytezz/mux"
		else:
			print bcolors.OKGREEN+"Your software is up to date."+bcolors.ENDC
		raw_input("<ENTER> to continue")
	elif q==".history":
		cls()
		if whis!="":
			whis.close()
		if not os.path.isfile(os.path.expanduser("~")+"/.mux/history.log"):
			open(os.path.expanduser("~")+"/.mux/history.log","w+").close()
		print "History ("+os.path.expanduser("~")+"/.mux/history.log):"
		his=open(os.path.expanduser("~")+"/.mux/history.log","r")
		print his.read()
		his.close()
		if whis!="":
			whis=open(os.path.expanduser("~")+"/.mux/history.log","a")
		raw_input("<ENTER> to continue")
	elif q==".history -c":
		if not os.path.isfile(os.path.expanduser("~")+"/.mux/history.log"):
			open(os.path.expanduser("~")+"/.mux/history.log","w+").close()
		his=open(os.path.expanduser("~")+"/.mux/history.log","w")
		his.write("")
		his.close()
	elif q==".exit" or q==".quit":
		if whis!="":
			whis.close()
		print "Bye."
		sys.exit()
	else:
		if whis!="":
			whis.write(str(time.time())+" - Looking for: "+q+"\n")
		print "Connecting..."
		html=urllib.urlopen(url+"?q="+gv(q)).read().replace("\n","").replace("\r","").replace("\t","")
		ul="".join(re.findall('<div id="results">(.*?)</div></div></div></div>',html))
		#r=re.findall('&amp;sort=artist" title="(.*?)</li>',ul)
		r=re.findall('" class="artist">(.*?)</a>',ul)
		rn=re.findall('</span><span class="title">(.*?)</span>',ul)
		rt=re.findall('<span class="time">(.*?)</span>',ul)
		#d=re.findall('</a> <a class="link" href="(.*?)" title="',ul)
		d=re.findall('&raquo;" href="(.*?)" target="_blank">',ul)
		if len(r)==0:
			print 'No results for "'+q+'"'
			#print html
			raw_input("<ENTER> to continue")
		else:
			global st
			st=str(len(rn))+' results for "'+q+'"'
			global n
			n=0
			com="..."
			while com!="s":
				if com=="...":
					rr(r,"")
				com=raw_input("> ")
				if com=="exit" or com==".exit" or com=="quit" or com==".quit":
					if whis!="":
						whis.close()
					print "Bye."
					sys.exit()
				elif com=="s":
					SystemExit
				elif com=="<" or com==">":
					rr(r,com)
				elif com.startswith("d "):
					for mf in com.split(" ")[1:]:
						if mf.isdigit():
							try:
								if int(mf)<len(r):
									if whis!="":
										whis.write(str(time.time())+" - Download: "+wsm()+ungv(d[int(mf)].split("/")[-1].split("?")[0])+"\n")
									print "Downloading number '"+mf+"' to '"+wsm()+ungv(d[int(mf)].split("/")[-1].split("?")[0])+"'..."
									f=open(wsm()+ungv(d[int(mf)].split("/")[-1].split("?")[0]),"w")
									f.write(urllib2.urlopen("https:"+d[int(mf)],context=ctx).read())
									f.close()
									print "Ok"
								else:
									print "'"+mf+"' out of index."
							except:
								print "'"+mf+"' out of index."
				elif com.split(" ")[0].isdigit():
					for com in com.split(" "):
						if com.isdigit():
							if int(com)<len(r):
								try:
									if whis!="":
										whis.write(str(time.time())+" - Play: "+ungv(d[int(com)].split("/")[-1].split("?")[0])+"\n")
									print "Playing '"+ungv(d[int(com)].split("/")[-1].split("?")[0])+"'"
									print r[int(com)]+"-"+rn[int(com)]+"-"+rt[int(com)]
									#Thread(target=strm("/tmp/"+ungv(d[int(com)].split("/")[-1].split("?")[0]),urllib.urlopen("https:"+d[int(com)]))).start()
									#Thread(target=plm("/tmp/"+ungv(d[int(com)].split("/")[-1].split("?")[0]),int(rt[int(com)].split(":")[0])*60+int(rt[int(com)].split(":")[1]))).start()
									strm("/tmp/"+ungv(d[int(com)].split("/")[-1].split("?")[0]),urllib2.urlopen("https:"+d[int(com)],context=ctx))
									plm("/tmp/"+ungv(d[int(com)].split("/")[-1].split("?")[0]),int(rt[int(com)].split(":")[0])*60+int(rt[int(com)].split(":")[1]))
								except Exception as e:
									print e
							else:
								print "'"+com+"' out of index."
				elif com.startswith("l "):
					for mf in com.split(" ")[1:]:
						if mf.isdigit():
							try:
								if int(mf)<len(r):
									print mf+" - "+"https:"+d[int(mf)]
								else:
									print "'"+mf+"' out of index."
							except:
								print "'"+mf+"' out of index."
				else:
					print "'"+com+"' not found."